sudo: false
language: php

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3

# yaml install
before_install:
  - pecl channel-update pecl.php.net
  - (CFLAGS="-O1 -g3 -fno-strict-aliasing"; pecl install yaml < /dev/null &)

addons:
  apt:
    packages:
      - libyaml-dev

install:
  - composer install

script: "php tests/run.php"
